name: 'Go swaggo/swag tool'
author: 'Yahor Rybchanka'
description: This action installs swag tool (https://github.com/swaggo/swag) to generate/test your golang application
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  swagVersion:
    description: 'Version of swag'
    required: false
    default: '1.8.1'
  command:
    description: 'swag command to execute. Optional'
    required: false
  equalToGoPath:
    description: 'Specifies a path to docs.go file you want to compare with your committed docs.go file'
    required: false
  equalToGoOriginPath:
    description: 'Specifies a path to docs.go file committed in the repository. Works only if "equalToGo" option is specified. Default is "docs/docs.go"'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
