name: 'Go swaggo/swag tool'
author: 'Yegor Rybchenko'
inputs:
  command:
    description: 'swag command to execute. Default is "init"'
    required: true
    default: 'init'
  swagWersion:
    description: 'Version of swag'
    required: false
    default: '1.8.1'
  equalToGo:
    description: 'Specifies a path to generated docs.go file is needed to be compared with your commited docs.go file'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
